### ISSUE TITLE
user experiences

### ISSUE THREAD

**Issue by neeltom92** [itprosource/terraform-aws-centralized-logging#1]
first of all kudos on the awesome work !!

please consider this as a suggestion to improve the user experience.

1. could you add further snapshots so while reading the README itself the reader can get understand it 
2. add architecture diagrams if possible

**Comment by itprosource** [comment]
Thanks for the feedback! I included an architecture diagram and expanded the readme with further instructions. Not much in the way of screenshots but I tried to make the instructions more comprehensive. If you have any further suggestions, don't hesitate to let me know.
